default_language_version:
  python: python3
repos:
  - repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --recursive
          - --remove-all-unused-imports
          - --ignore-init-module-imports
          - --expand-star-imports
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.1.0
    hooks:
      - id: black
